In [5]:
import numpy as np

In [6]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [7]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [8]:
a.shape

(5, 2)

In [9]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [10]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [11]:
a_centered.shape

(5, 2)

In [13]:
a1=a_centered[:,0]

a2=a_centered[:,1]

a_centered_sp=np.dot(a1,a2)

a_centered_sp

8.0

In [17]:
N=a.shape[0]
N

a_sentered_sp_1 = a_centered_sp/(N-1)
a_sentered_sp_1

2.0

In [18]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])